// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Range.proto

#ifndef PROTOBUF_Range_2eproto__INCLUDED
#define PROTOBUF_Range_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "Stamp.pb.h"
// @@protoc_insertion_point(includes)

namespace MaxBotMessages {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Range_2eproto();
void protobuf_AssignDesc_Range_2eproto();
void protobuf_ShutdownFile_Range_2eproto();

class Range;
class RangeStamped;

// ===================================================================

class Range : public ::google::protobuf::Message {
 public:
  Range();
  virtual ~Range();

  Range(const Range& from);

  inline Range& operator=(const Range& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Range& default_instance();

  void Swap(Range* other);

  // implements Message ----------------------------------------------

  Range* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Range& from);
  void MergeFrom(const Range& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required double value = 1;
  inline bool has_value() const;
  inline void clear_value();
  static const int kValueFieldNumber = 1;
  inline double value() const;
  inline void set_value(double value);

  // @@protoc_insertion_point(class_scope:MaxBotMessages.Range)
 private:
  inline void set_has_value();
  inline void clear_has_value();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double value_;
  friend void  protobuf_AddDesc_Range_2eproto();
  friend void protobuf_AssignDesc_Range_2eproto();
  friend void protobuf_ShutdownFile_Range_2eproto();

  void InitAsDefaultInstance();
  static Range* default_instance_;
};
// -------------------------------------------------------------------

class RangeStamped : public ::google::protobuf::Message {
 public:
  RangeStamped();
  virtual ~RangeStamped();

  RangeStamped(const RangeStamped& from);

  inline RangeStamped& operator=(const RangeStamped& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RangeStamped& default_instance();

  void Swap(RangeStamped* other);

  // implements Message ----------------------------------------------

  RangeStamped* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RangeStamped& from);
  void MergeFrom(const RangeStamped& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .MaxBotMessages.Stamp stamp = 1;
  inline bool has_stamp() const;
  inline void clear_stamp();
  static const int kStampFieldNumber = 1;
  inline const ::MaxBotMessages::Stamp& stamp() const;
  inline ::MaxBotMessages::Stamp* mutable_stamp();
  inline ::MaxBotMessages::Stamp* release_stamp();
  inline void set_allocated_stamp(::MaxBotMessages::Stamp* stamp);

  // required .MaxBotMessages.Range range = 2;
  inline bool has_range() const;
  inline void clear_range();
  static const int kRangeFieldNumber = 2;
  inline const ::MaxBotMessages::Range& range() const;
  inline ::MaxBotMessages::Range* mutable_range();
  inline ::MaxBotMessages::Range* release_range();
  inline void set_allocated_range(::MaxBotMessages::Range* range);

  // @@protoc_insertion_point(class_scope:MaxBotMessages.RangeStamped)
 private:
  inline void set_has_stamp();
  inline void clear_has_stamp();
  inline void set_has_range();
  inline void clear_has_range();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::MaxBotMessages::Stamp* stamp_;
  ::MaxBotMessages::Range* range_;
  friend void  protobuf_AddDesc_Range_2eproto();
  friend void protobuf_AssignDesc_Range_2eproto();
  friend void protobuf_ShutdownFile_Range_2eproto();

  void InitAsDefaultInstance();
  static RangeStamped* default_instance_;
};
// ===================================================================


// ===================================================================

// Range

// required double value = 1;
inline bool Range::has_value() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Range::set_has_value() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Range::clear_has_value() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Range::clear_value() {
  value_ = 0;
  clear_has_value();
}
inline double Range::value() const {
  // @@protoc_insertion_point(field_get:MaxBotMessages.Range.value)
  return value_;
}
inline void Range::set_value(double value) {
  set_has_value();
  value_ = value;
  // @@protoc_insertion_point(field_set:MaxBotMessages.Range.value)
}

// -------------------------------------------------------------------

// RangeStamped

// required .MaxBotMessages.Stamp stamp = 1;
inline bool RangeStamped::has_stamp() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RangeStamped::set_has_stamp() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RangeStamped::clear_has_stamp() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RangeStamped::clear_stamp() {
  if (stamp_ != NULL) stamp_->::MaxBotMessages::Stamp::Clear();
  clear_has_stamp();
}
inline const ::MaxBotMessages::Stamp& RangeStamped::stamp() const {
  // @@protoc_insertion_point(field_get:MaxBotMessages.RangeStamped.stamp)
  return stamp_ != NULL ? *stamp_ : *default_instance_->stamp_;
}
inline ::MaxBotMessages::Stamp* RangeStamped::mutable_stamp() {
  set_has_stamp();
  if (stamp_ == NULL) stamp_ = new ::MaxBotMessages::Stamp;
  // @@protoc_insertion_point(field_mutable:MaxBotMessages.RangeStamped.stamp)
  return stamp_;
}
inline ::MaxBotMessages::Stamp* RangeStamped::release_stamp() {
  clear_has_stamp();
  ::MaxBotMessages::Stamp* temp = stamp_;
  stamp_ = NULL;
  return temp;
}
inline void RangeStamped::set_allocated_stamp(::MaxBotMessages::Stamp* stamp) {
  delete stamp_;
  stamp_ = stamp;
  if (stamp) {
    set_has_stamp();
  } else {
    clear_has_stamp();
  }
  // @@protoc_insertion_point(field_set_allocated:MaxBotMessages.RangeStamped.stamp)
}

// required .MaxBotMessages.Range range = 2;
inline bool RangeStamped::has_range() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RangeStamped::set_has_range() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RangeStamped::clear_has_range() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RangeStamped::clear_range() {
  if (range_ != NULL) range_->::MaxBotMessages::Range::Clear();
  clear_has_range();
}
inline const ::MaxBotMessages::Range& RangeStamped::range() const {
  // @@protoc_insertion_point(field_get:MaxBotMessages.RangeStamped.range)
  return range_ != NULL ? *range_ : *default_instance_->range_;
}
inline ::MaxBotMessages::Range* RangeStamped::mutable_range() {
  set_has_range();
  if (range_ == NULL) range_ = new ::MaxBotMessages::Range;
  // @@protoc_insertion_point(field_mutable:MaxBotMessages.RangeStamped.range)
  return range_;
}
inline ::MaxBotMessages::Range* RangeStamped::release_range() {
  clear_has_range();
  ::MaxBotMessages::Range* temp = range_;
  range_ = NULL;
  return temp;
}
inline void RangeStamped::set_allocated_range(::MaxBotMessages::Range* range) {
  delete range_;
  range_ = range;
  if (range) {
    set_has_range();
  } else {
    clear_has_range();
  }
  // @@protoc_insertion_point(field_set_allocated:MaxBotMessages.RangeStamped.range)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace MaxBotMessages

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Range_2eproto__INCLUDED
