// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Stamp.proto

#ifndef PROTOBUF_Stamp_2eproto__INCLUDED
#define PROTOBUF_Stamp_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace MaxBotMessages {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_Stamp_2eproto();
void protobuf_AssignDesc_Stamp_2eproto();
void protobuf_ShutdownFile_Stamp_2eproto();

class Stamp;

enum MeasurementType {
  ABSOLUTE = 0,
  DIFFERENTIAL = 1
};
bool MeasurementType_IsValid(int value);
const MeasurementType MeasurementType_MIN = ABSOLUTE;
const MeasurementType MeasurementType_MAX = DIFFERENTIAL;
const int MeasurementType_ARRAYSIZE = MeasurementType_MAX + 1;

const ::google::protobuf::EnumDescriptor* MeasurementType_descriptor();
inline const ::std::string& MeasurementType_Name(MeasurementType value) {
  return ::google::protobuf::internal::NameOfEnum(
    MeasurementType_descriptor(), value);
}
inline bool MeasurementType_Parse(
    const ::std::string& name, MeasurementType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MeasurementType>(
    MeasurementType_descriptor(), name, value);
}
// ===================================================================

class Stamp : public ::google::protobuf::Message {
 public:
  Stamp();
  virtual ~Stamp();

  Stamp(const Stamp& from);

  inline Stamp& operator=(const Stamp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Stamp& default_instance();

  void Swap(Stamp* other);

  // implements Message ----------------------------------------------

  inline Stamp* New() const { return New(NULL); }

  Stamp* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Stamp& from);
  void MergeFrom(const Stamp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Stamp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string component_id = 1;
  bool has_component_id() const;
  void clear_component_id();
  static const int kComponentIdFieldNumber = 1;
  const ::std::string& component_id() const;
  void set_component_id(const ::std::string& value);
  void set_component_id(const char* value);
  void set_component_id(const char* value, size_t size);
  ::std::string* mutable_component_id();
  ::std::string* release_component_id();
  void set_allocated_component_id(::std::string* component_id);

  // required int64 time = 2;
  bool has_time() const;
  void clear_time();
  static const int kTimeFieldNumber = 2;
  ::google::protobuf::int64 time() const;
  void set_time(::google::protobuf::int64 value);

  // optional .MaxBotMessages.MeasurementType measurement_type = 3 [default = ABSOLUTE];
  bool has_measurement_type() const;
  void clear_measurement_type();
  static const int kMeasurementTypeFieldNumber = 3;
  ::MaxBotMessages::MeasurementType measurement_type() const;
  void set_measurement_type(::MaxBotMessages::MeasurementType value);

  // @@protoc_insertion_point(class_scope:MaxBotMessages.Stamp)
 private:
  inline void set_has_component_id();
  inline void clear_has_component_id();
  inline void set_has_time();
  inline void clear_has_time();
  inline void set_has_measurement_type();
  inline void clear_has_measurement_type();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr component_id_;
  ::google::protobuf::int64 time_;
  int measurement_type_;
  friend void  protobuf_AddDesc_Stamp_2eproto();
  friend void protobuf_AssignDesc_Stamp_2eproto();
  friend void protobuf_ShutdownFile_Stamp_2eproto();

  void InitAsDefaultInstance();
  static Stamp* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Stamp

// required string component_id = 1;
inline bool Stamp::has_component_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Stamp::set_has_component_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Stamp::clear_has_component_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Stamp::clear_component_id() {
  component_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_component_id();
}
inline const ::std::string& Stamp::component_id() const {
  // @@protoc_insertion_point(field_get:MaxBotMessages.Stamp.component_id)
  return component_id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Stamp::set_component_id(const ::std::string& value) {
  set_has_component_id();
  component_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MaxBotMessages.Stamp.component_id)
}
inline void Stamp::set_component_id(const char* value) {
  set_has_component_id();
  component_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MaxBotMessages.Stamp.component_id)
}
inline void Stamp::set_component_id(const char* value, size_t size) {
  set_has_component_id();
  component_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MaxBotMessages.Stamp.component_id)
}
inline ::std::string* Stamp::mutable_component_id() {
  set_has_component_id();
  // @@protoc_insertion_point(field_mutable:MaxBotMessages.Stamp.component_id)
  return component_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Stamp::release_component_id() {
  clear_has_component_id();
  return component_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Stamp::set_allocated_component_id(::std::string* component_id) {
  if (component_id != NULL) {
    set_has_component_id();
  } else {
    clear_has_component_id();
  }
  component_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), component_id);
  // @@protoc_insertion_point(field_set_allocated:MaxBotMessages.Stamp.component_id)
}

// required int64 time = 2;
inline bool Stamp::has_time() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Stamp::set_has_time() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Stamp::clear_has_time() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Stamp::clear_time() {
  time_ = GOOGLE_LONGLONG(0);
  clear_has_time();
}
inline ::google::protobuf::int64 Stamp::time() const {
  // @@protoc_insertion_point(field_get:MaxBotMessages.Stamp.time)
  return time_;
}
inline void Stamp::set_time(::google::protobuf::int64 value) {
  set_has_time();
  time_ = value;
  // @@protoc_insertion_point(field_set:MaxBotMessages.Stamp.time)
}

// optional .MaxBotMessages.MeasurementType measurement_type = 3 [default = ABSOLUTE];
inline bool Stamp::has_measurement_type() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Stamp::set_has_measurement_type() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Stamp::clear_has_measurement_type() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Stamp::clear_measurement_type() {
  measurement_type_ = 0;
  clear_has_measurement_type();
}
inline ::MaxBotMessages::MeasurementType Stamp::measurement_type() const {
  // @@protoc_insertion_point(field_get:MaxBotMessages.Stamp.measurement_type)
  return static_cast< ::MaxBotMessages::MeasurementType >(measurement_type_);
}
inline void Stamp::set_measurement_type(::MaxBotMessages::MeasurementType value) {
  assert(::MaxBotMessages::MeasurementType_IsValid(value));
  set_has_measurement_type();
  measurement_type_ = value;
  // @@protoc_insertion_point(field_set:MaxBotMessages.Stamp.measurement_type)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace MaxBotMessages

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::MaxBotMessages::MeasurementType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::MaxBotMessages::MeasurementType>() {
  return ::MaxBotMessages::MeasurementType_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Stamp_2eproto__INCLUDED
