// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Stamp.proto

#ifndef PROTOBUF_Stamp_2eproto__INCLUDED
#define PROTOBUF_Stamp_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace MaxBotMessages {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Stamp_2eproto();
void protobuf_AssignDesc_Stamp_2eproto();
void protobuf_ShutdownFile_Stamp_2eproto();

class Stamp;

// ===================================================================

class Stamp : public ::google::protobuf::Message {
 public:
  Stamp();
  virtual ~Stamp();

  Stamp(const Stamp& from);

  inline Stamp& operator=(const Stamp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Stamp& default_instance();

  void Swap(Stamp* other);

  // implements Message ----------------------------------------------

  Stamp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Stamp& from);
  void MergeFrom(const Stamp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string component_id = 1;
  inline bool has_component_id() const;
  inline void clear_component_id();
  static const int kComponentIdFieldNumber = 1;
  inline const ::std::string& component_id() const;
  inline void set_component_id(const ::std::string& value);
  inline void set_component_id(const char* value);
  inline void set_component_id(const char* value, size_t size);
  inline ::std::string* mutable_component_id();
  inline ::std::string* release_component_id();
  inline void set_allocated_component_id(::std::string* component_id);

  // required int32 milliseconds_since_epoch = 2;
  inline bool has_milliseconds_since_epoch() const;
  inline void clear_milliseconds_since_epoch();
  static const int kMillisecondsSinceEpochFieldNumber = 2;
  inline ::google::protobuf::int32 milliseconds_since_epoch() const;
  inline void set_milliseconds_since_epoch(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:MaxBotMessages.Stamp)
 private:
  inline void set_has_component_id();
  inline void clear_has_component_id();
  inline void set_has_milliseconds_since_epoch();
  inline void clear_has_milliseconds_since_epoch();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* component_id_;
  ::google::protobuf::int32 milliseconds_since_epoch_;
  friend void  protobuf_AddDesc_Stamp_2eproto();
  friend void protobuf_AssignDesc_Stamp_2eproto();
  friend void protobuf_ShutdownFile_Stamp_2eproto();

  void InitAsDefaultInstance();
  static Stamp* default_instance_;
};
// ===================================================================


// ===================================================================

// Stamp

// required string component_id = 1;
inline bool Stamp::has_component_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Stamp::set_has_component_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Stamp::clear_has_component_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Stamp::clear_component_id() {
  if (component_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    component_id_->clear();
  }
  clear_has_component_id();
}
inline const ::std::string& Stamp::component_id() const {
  // @@protoc_insertion_point(field_get:MaxBotMessages.Stamp.component_id)
  return *component_id_;
}
inline void Stamp::set_component_id(const ::std::string& value) {
  set_has_component_id();
  if (component_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    component_id_ = new ::std::string;
  }
  component_id_->assign(value);
  // @@protoc_insertion_point(field_set:MaxBotMessages.Stamp.component_id)
}
inline void Stamp::set_component_id(const char* value) {
  set_has_component_id();
  if (component_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    component_id_ = new ::std::string;
  }
  component_id_->assign(value);
  // @@protoc_insertion_point(field_set_char:MaxBotMessages.Stamp.component_id)
}
inline void Stamp::set_component_id(const char* value, size_t size) {
  set_has_component_id();
  if (component_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    component_id_ = new ::std::string;
  }
  component_id_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:MaxBotMessages.Stamp.component_id)
}
inline ::std::string* Stamp::mutable_component_id() {
  set_has_component_id();
  if (component_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    component_id_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:MaxBotMessages.Stamp.component_id)
  return component_id_;
}
inline ::std::string* Stamp::release_component_id() {
  clear_has_component_id();
  if (component_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = component_id_;
    component_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Stamp::set_allocated_component_id(::std::string* component_id) {
  if (component_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete component_id_;
  }
  if (component_id) {
    set_has_component_id();
    component_id_ = component_id;
  } else {
    clear_has_component_id();
    component_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:MaxBotMessages.Stamp.component_id)
}

// required int32 milliseconds_since_epoch = 2;
inline bool Stamp::has_milliseconds_since_epoch() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Stamp::set_has_milliseconds_since_epoch() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Stamp::clear_has_milliseconds_since_epoch() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Stamp::clear_milliseconds_since_epoch() {
  milliseconds_since_epoch_ = 0;
  clear_has_milliseconds_since_epoch();
}
inline ::google::protobuf::int32 Stamp::milliseconds_since_epoch() const {
  // @@protoc_insertion_point(field_get:MaxBotMessages.Stamp.milliseconds_since_epoch)
  return milliseconds_since_epoch_;
}
inline void Stamp::set_milliseconds_since_epoch(::google::protobuf::int32 value) {
  set_has_milliseconds_since_epoch();
  milliseconds_since_epoch_ = value;
  // @@protoc_insertion_point(field_set:MaxBotMessages.Stamp.milliseconds_since_epoch)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace MaxBotMessages

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Stamp_2eproto__INCLUDED
