// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Stamp.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Stamp.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace MaxBotMessages {

namespace {

const ::google::protobuf::Descriptor* Stamp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Stamp_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_Stamp_2eproto() {
  protobuf_AddDesc_Stamp_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "Stamp.proto");
  GOOGLE_CHECK(file != NULL);
  Stamp_descriptor_ = file->message_type(0);
  static const int Stamp_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Stamp, component_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Stamp, milliseconds_since_epoch_),
  };
  Stamp_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Stamp_descriptor_,
      Stamp::default_instance_,
      Stamp_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Stamp, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Stamp, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Stamp));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_Stamp_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Stamp_descriptor_, &Stamp::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_Stamp_2eproto() {
  delete Stamp::default_instance_;
  delete Stamp_reflection_;
}

void protobuf_AddDesc_Stamp_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013Stamp.proto\022\016MaxBotMessages\"\?\n\005Stamp\022\024"
    "\n\014component_id\030\001 \002(\t\022 \n\030milliseconds_sin"
    "ce_epoch\030\002 \002(\005", 94);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Stamp.proto", &protobuf_RegisterTypes);
  Stamp::default_instance_ = new Stamp();
  Stamp::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_Stamp_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_Stamp_2eproto {
  StaticDescriptorInitializer_Stamp_2eproto() {
    protobuf_AddDesc_Stamp_2eproto();
  }
} static_descriptor_initializer_Stamp_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Stamp::kComponentIdFieldNumber;
const int Stamp::kMillisecondsSinceEpochFieldNumber;
#endif  // !_MSC_VER

Stamp::Stamp()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MaxBotMessages.Stamp)
}

void Stamp::InitAsDefaultInstance() {
}

Stamp::Stamp(const Stamp& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MaxBotMessages.Stamp)
}

void Stamp::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  component_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  milliseconds_since_epoch_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Stamp::~Stamp() {
  // @@protoc_insertion_point(destructor:MaxBotMessages.Stamp)
  SharedDtor();
}

void Stamp::SharedDtor() {
  if (component_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete component_id_;
  }
  if (this != default_instance_) {
  }
}

void Stamp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Stamp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Stamp_descriptor_;
}

const Stamp& Stamp::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Stamp_2eproto();
  return *default_instance_;
}

Stamp* Stamp::default_instance_ = NULL;

Stamp* Stamp::New() const {
  return new Stamp;
}

void Stamp::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    if (has_component_id()) {
      if (component_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        component_id_->clear();
      }
    }
    milliseconds_since_epoch_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Stamp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MaxBotMessages.Stamp)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string component_id = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_component_id()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->component_id().data(), this->component_id().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "component_id");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_milliseconds_since_epoch;
        break;
      }

      // required int32 milliseconds_since_epoch = 2;
      case 2: {
        if (tag == 16) {
         parse_milliseconds_since_epoch:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &milliseconds_since_epoch_)));
          set_has_milliseconds_since_epoch();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MaxBotMessages.Stamp)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MaxBotMessages.Stamp)
  return false;
#undef DO_
}

void Stamp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MaxBotMessages.Stamp)
  // required string component_id = 1;
  if (has_component_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->component_id().data(), this->component_id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "component_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->component_id(), output);
  }

  // required int32 milliseconds_since_epoch = 2;
  if (has_milliseconds_since_epoch()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->milliseconds_since_epoch(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MaxBotMessages.Stamp)
}

::google::protobuf::uint8* Stamp::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MaxBotMessages.Stamp)
  // required string component_id = 1;
  if (has_component_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->component_id().data(), this->component_id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "component_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->component_id(), target);
  }

  // required int32 milliseconds_since_epoch = 2;
  if (has_milliseconds_since_epoch()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->milliseconds_since_epoch(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MaxBotMessages.Stamp)
  return target;
}

int Stamp::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string component_id = 1;
    if (has_component_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->component_id());
    }

    // required int32 milliseconds_since_epoch = 2;
    if (has_milliseconds_since_epoch()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->milliseconds_since_epoch());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Stamp::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Stamp* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Stamp*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Stamp::MergeFrom(const Stamp& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_component_id()) {
      set_component_id(from.component_id());
    }
    if (from.has_milliseconds_since_epoch()) {
      set_milliseconds_since_epoch(from.milliseconds_since_epoch());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Stamp::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Stamp::CopyFrom(const Stamp& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Stamp::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void Stamp::Swap(Stamp* other) {
  if (other != this) {
    std::swap(component_id_, other->component_id_);
    std::swap(milliseconds_since_epoch_, other->milliseconds_since_epoch_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Stamp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Stamp_descriptor_;
  metadata.reflection = Stamp_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace MaxBotMessages

// @@protoc_insertion_point(global_scope)
